import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import SelectWindow from '../components/organisms/SelectWindow'
import styles from '../styles/Home.module.css'
import * as tf from "@tensorflow/tfjs";
import '@tensorflow/tfjs-backend-webgl';
import "@tensorflow/tfjs-backend-wasm";
import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm'


const Home: NextPage = () => {

  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SelectWindow />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )

}

export default Home
